import { booleanPointInPolygon } from '@turf/boolean-point-in-polygon'
import { point } from '@turf/helpers'
import type { Coordinates } from '../types'
import type { DatasetId } from '../types/workspace'
import andaluciaBoundary from '../data/andalucia-boundary.json'

export interface CoverageRegion {
  id: string
  status: 'available'
  /**
   * The datasets that can return something in this region.
   *
   * This gates which datasets are fetched at all, so it means "capable of an
   * answer here", not "guaranteed to have one" — `waterQuality` and
   * `reservoirs` are curated municipality by municipality and legitimately come
   * back empty for places not yet researched. What it must never list is a
   * dataset that cannot answer anywhere, which is why `groundwater` is absent.
   */
  datasets: DatasetId[]
  effectiveDate: string
  geometry: GeoJSON.Feature<GeoJSON.Polygon | GeoJSON.MultiPolygon>
}

export interface CoverageResult {
  supported: boolean
  regionId?: string
  datasets: DatasetId[]
}

const REGIONS: CoverageRegion[] = [
  {
    id: 'andalucia',
    status: 'available',
    // `groundwater` is deliberately not here: its source data was fabricated
    // and has been removed, and no live service publishes a replacement (see
    // services/groundwater.ts). Listing it would have the coverage box promise
    // a check that cannot run.
    datasets: ['flood', 'drought', 'reservoirs', 'waterQuality', 'coastalFlood', 'bathingWater'],
    effectiveDate: '2026-07-30',
    // NOTE (verified 2026-07): the real administrative boundary, from OSM via
    // scripts/fetch-andalucia-boundary.mjs. The 24-point sketch this replaced
    // put Tarifa — mainland Spain's southernmost town, in Cádiz — outside
    // coverage entirely.
    geometry: andaluciaBoundary as GeoJSON.Feature<GeoJSON.Polygon | GeoJSON.MultiPolygon>,
  },
]

export function lookupCoverage(coords: Coordinates): CoverageResult {
  const pt = point([coords.lng, coords.lat])
  for (const region of REGIONS) {
    if (booleanPointInPolygon(pt, region.geometry)) {
      return { supported: true, regionId: region.id, datasets: region.datasets }
    }
  }
  return { supported: false, datasets: [] }
}

export function getCoverageGeoJSON(): GeoJSON.FeatureCollection {
  // `regionId` is stamped here rather than trusted from the geometry file:
  // the boundary is regenerated by script from OSM, and a property the map
  // depends on must not depend on that file happening to carry it.
  return {
    type: 'FeatureCollection',
    features: REGIONS.map(r => ({
      ...r.geometry,
      properties: { ...r.geometry.properties, regionId: r.id },
    })),
  }
}
